on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t rendalo-test .
      - name: Run Test
        run: |
          docker run --rm rendalo-test pytest
